Anchor names are too generic and clash between server and client
If one tries to use the apt_cacher_ng module to setup a server and
client on the same machine, the following error can be seen:

Error: Could not retrieve catalog from remote server: Error 400 on
SERVER: Duplicate declaration: Anchor[begin] is already declared in file
/etc/puppet/environments/production/modules/apt_cacher_ng/manifests/client.pp:21;
cannot redeclare at
/etc/puppet/environments/production/modules/apt_cacher_ng/manifests/init.pp:18
on node debianpackages-vm-inx01.intra.local.ch

This is also problematic with other modules that might declare anchors
with the same name, so the solution is to use the module and class name
to create a namespace for the anchors.